# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Download Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Mediafire
      run: python prog.py download https://www.mediafire.com/file/pygk38vfgykmm3u/Dummy.txt/file
    - name: Solidfiles
      run: python prog.py download https://www.solidfiles.com/v/Lger2566WXWxk
    - name: Racaty
      run: python prog.py download https://racaty.net/1tcu5sr8k5z6
    - name: Anonfiles
      run: python prog.py download https://anonfiles.com/jbC8Wak9y6/Dummy_zip
    - name: Bayfiles
      run: python prog.py download https://bayfiles.com/JeK5W5kcyb/Dummy_zip
    - name: Zippyshare
      run: python prog.py download https://www42.zippyshare.com/v/wRdO7y1A/file.html
    - name: Hxfile
      run: python prog.py download https://hxfile.co/dpnia0tpgmao
        
