# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Python App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test to download a dummy file
      run: |
        echo "Mediafire"
        python prog.py download https://www.mediafire.com/file/pygk38vfgykmm3u/Dummy.txt/file
        echo "Solidfiles"
        python prog.py download https://www.solidfiles.com/v/Lger2566WXWxk
        echo "Racaty"
        python prog.py download https://racaty.net/5ng0nisvvgo7
        echo "Anonfiles"
        python prog.py download https://anonfiles.com/z0PeVckby2/Dummy_txt
        echo "Bayfiles"
        python prog.py download https://bayfiles.com/H2Q6V6k3yd/Dummy_txt
        echo "Zippyshare"
        python prog.py download https://www42.zippyshare.com/v/wRdO7y1A/file.html
        
