# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Download Test

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Mediafire
      run: python prog.py download -nt -o -t 8 https://www.mediafire.com/file/pygk38vfgykmm3u/Dummy.txt/file
    - name: Solidfiles
      run: python prog.py download -nt -o -t 8 https://www.solidfiles.com/v/A3qk56rZNPZGg
    - name: Anonfiles
      run: python prog.py download -nt -o -t 8 https://anonfiles.com/6ded8d44y7/20220820_135747_1_png
#Anonfiles as same as Bayfiles
    - name: Zippyshare
      run: python prog.py download -nt -o -t 8 https://www6.zippyshare.com/v/gZ7oM3DH/file.html
    - name: Hxfile
      run: python prog.py download -nt -o -t 8 https://hxfile.co/41gk09mhtc89
    - name: Tusfiles
      run: python prog.py download -nt -o -t 8 https://tusfiles.com/t6w03a6ovojz
